### ISSUE TITLE
Add fertilizer to cactus and sugarcane

### ISSUE THREAD

**Issue by gipsy-king** [Civcraft/RealisticBiomes#91]
Don't know if this should be a github issue. I can post to e.g. modmail and close this if you prefer.

Add fertilizers to sugarcane and cactus, to make farms a bit more complex and interesting. The final growth with full fertilizer should stay the same as before, it would then only grow slower without the soil.

I tested locally, and propose the following:

```yaml
  column:
   ...
   # four layers
   soil_max_layers: 4
   soil_bonus_per_layer: 0.5
   # include the block directly below the plant, unlike crops which require farmland:
   soil_layer_offset: 1

  CACTUS:
   inherit: column
   persistent_growth_period: <3 times the previous value>
   # this is red sand, regular sand would be too easy for deserts:
   soil_material: SAND:1
   biomes:
    ...

  SUGAR_CANE_BLOCK:
   inherit: column
   persistent_growth_period: <3 times the previous value>
   # sand, because historically when sugarcane was introduced it only grew on sand (and lets not use clay again):
   soil_material: SAND
   biomes:
    ...
```
